go-resty/resty

client.go, default.go, middleware.go, resty_test.go
Signed-off-by: André Martins <aanm90@gmail.com>
=> Add set scheme client option

client.go, default.go, middleware.go, resty_test.go
Signed-off-by: André Martins <aanm90@gmail.com>
=> Option to close connection for each HTTP request

README.md
Signed-off-by: André Martins <aanm90@gmail.com>
=> Added unix socket example

.travis.yml, README.md, middleware.go, request.go, resty_test.go
=> SetMultiValueFormData method added

context17_test.go, context18_test.go, context_test.go, middleware.go, request.go, request16.go, request17.go, resty_test.go
=> Add Request.SetContext

middleware.go, request.go, request16.go, request17.go, resty_test.go
I've made this changes to be possible to do a request based on the SRV record of the service. It is useful when you have a service discovery mechanism, like Consul, so you can pass the information and the system will query the SRV record and to the request based on it.
I do not expect this PR to be merged right away, but to start a discussion on the following topic.
Please, review it and suggest the needed changes.
=> Request based on the SRV record of the service

client.go, client12.go, client13.go, client_test.go, resty_test.go
fix(#59) by using `http.Client.Timeout` instead of a special `http.Transport`.
=> Use HTTP Client SetTimeout instead of custom timeout

README.md, client.go, default.go, request.go, resty_test.go, retry.go, retry_test.go
This resolves #64 
Changes made here:
- Changing retry wait time options to have `time.Duration` type instead of of `int` holding milliseconds.
- Adding `RetryWaitTime` and `RetryMaxWaitTime` fields to `Client` along with chaining setters.
- A condition to make sure `Backoff` always sleeps at least `WaitTime` duration. Before this change it could sleep less than this due to jitter we have there. Especially before the very first retry, the sleep duration was always somewhere between `WaitTime / 2` and `WaitTime`.
- Test to make sure overridden wait times are actually used.
=> Allow to override default retry wait times for Client

client.go, client_test.go, default.go
* allow user override default CookieJar in resty client
=> add SetCookieJar method

client.go, default.go, request.go, resty_test.go
Rewire set methods to actual url.Values' set methods for:
- setFormData
- setQueryParams
+ a few typo fix
=> Rewire set methods to actual url.Values' set methods

client_test.go, default.go, resty_test.go
Just noticed we have these package level shortcuts for configuring DefaultClient and added them for retry timeouts.
=> Add shortcuts to set DefaultClient's retry timeouts

middleware.go
some monitoring software has to prioritize User-Agent, X-User-Agent or possibly some query string parameter where youd typically rank qs and X-User-Agent a higher prio than the normal UA because in some environments (browsers) you cant set the UA.
In such a (not uncommon) setup "resty" would show up as the UA which is not helpful at all. The user of resty already supplies a UA, there is no need to add another header with the resty UA.
=> Why set a UA if one is already supplied

README.md, client.go, client_test.go, default.go, middleware.go, request.go, resty_test.go
Implements `SetAllowGetMethodPayload()` on `go-resty` client to
allow developer decides if request includes payload with GET method.
fixes #81
=> Adds an option to support GET method with request body

.travis.yml, client.go, default.go, request.go, request16.go, request17.go, response.go, resty.go, resty_test.go
=> Expose response body

client.go, client_test.go, default.go, resty_test.go, retry_test.go
=> Added support http.RoundTripper

README.md
according to #56  the Request Level Proxy is removed.
=> remove Request level proxy

client.go, client_test.go, default.go, resty_test.go
=> Log prefix enhancement

request_test.go, resty_test.go, util.go
We use `REPORT` and [other HTTP methods](https://www.iana.org/assignments/http-methods/http-methods.xhtml) as part of our REST API for their defined semantics. The `REPORT` method is defined to support a request body. I've refactored `isPayloadSupported` to explicitly look for the standard HTTP methods that are defined as not supporting request bodies so that uncommon HTTP methods may support request bodies, too.
=> Allow uncommon HTTP methods to support payloads

middleware.go, request.go, request_test.go
=> Preserve query string order partially

middleware.go
The debug logs become unreadable for concurrent requests made with resty. Here's some code which demonstrates the issue:
```go
package main
import (
"sync"
"time"
resty "gopkg.in/resty.v1"
)
func main() {
client := resty.New().
SetHostURL("https://jsonplaceholder.typicode.com").
SetDebug(true).
SetDebugBodyLimit(10000).
SetTimeout(time.Minute).
SetContentLength(true).
SetHeaders(map[string]string{
"Content-Type": "application/json; charset=utf-8",
"Accept":       "application/json; charset=utf-8",
})
var wg sync.WaitGroup
wg.Add(3)
go func() {
defer wg.Done()
client.R().Get("/posts/1")
}()
go func() {
defer wg.Done()
client.R().Get("/posts/2")
}()
go func() {
defer wg.Done()
client.R().Get("/posts/3")
}()
wg.Wait()
}
```
<details>
<summary>debug logs (before)</summary>
```
λ go run …
```
=> Debug log with concatenated string

client.go, middleware.go, request.go, request16.go, request17.go, request_test.go, util.go
Proposal for `MultipartCustomData` type, in case there's a need to inject custom data into multipart request. Since `SetFile()` and `SetFileReader()` functions are specifically file-oriented, I created a separate type to hold `Content-Disposition` header fields, `Content-Type` and the actual data.
=> Custom data for multipart request

middleware.go
=> #131 fix missing query params on relative path request

README.md, client.go, request_test.go, resty_test.go
=> #134 added support for rfc7807 - application/problem+json and application/problem+xml

README.md, middleware.go, request.go, request_test.go, resty_test.go
=> Buffer less Large file support on body

BUILD.bazel, README.md, WORKSPACE
Adding a basic workspace and bazel rules.
The rules were generated via gazelle (blaze run :gazelle) and tuned a bit (e.g. changing visibility and adding the data dependency).
This should allow bazel users to just depend on the project without a local BUILD file.
=> Add support for bazel build rules

client_test.go, request_test.go, resty_test.go
Use filepath when constructing local file paths.  Don't test Error()
text since it's platform specific for DNS errors; rather, test for type
net.DNSError.
=> Fixes test failures in Windows

client.go, client_test.go, resty_test.go
=> #142 added fallback gzip response handling

client.go, request_test.go, resty_test.go
This is a proposed fix for #155.
=> Add support for overriding the header.

BUILD.bazel, WORKSPACE
Some cleanups on the workspace definition (e.g. depending on labels).
Updated the structure to work with 0.13.0, removing go_prefix.
Moved file targeting to globs to be more future proof.
=> Update bazel definitions to work with release 0.13.0, following up on #140

client.go, util_test.go
The existing IsJSONType and IsXMLType regular expressions are here
generalized to work with any properly formatted media type.
=> Make IsJSONType and IsXMLType more robust

client.go
=> #175 fix default user-agent string format

client.go, default.go, middleware.go, request.go, request16.go, request17.go, request_test.go, util.go
=> Added option to disable/enable html escape on json marshal

client.go, client_test.go, middleware.go, util.go
=> #180 #182 debug log callback added to customize log info before logging

client.go
Resolves #187
Skip decompression if the Content-Length is 0 specifically. Chunked gzipped responses can return a Content-Length of -1 to specify an unknown size.
=> Only skip decompression if the Content-Length is 0.

util.go
=> mark slices as valid for json marshalling

client.go, request.go, request16.go, request17.go, request_test.go, util.go
Dear Jeevanandam,
Thank you for your great library. I would like to propose you this small improvement.
The idea is to add SetMultipartFields method to set multiple fields. Sometimes it is convenient to prepare list with some hardcoded fields at top of request processing function in declarative way and then pass it to request. Resty API already has similar functions: SetHeaders and SetFiles.
Example of usage SetMultipartFields method (extracted from comment):
```
fields := []*MultipartField{
&MultipartField{
Param:       "uploadManifest1",
FileName:    "upload-file-1.json",
ContentType: "application/json",
Reader:      strings.NewReader(`{"input": {"name": "Uploaded document 1", "_filename" : ["file1.txt"]}}`),
},
&MultipartField{
Param:       "uploadManifest2",
FileName: …
```
=>  Add batch SetMultipartFields in order to set multiple fields

client.go, request.go, retry.go, retry_test.go
1) Add capabilities to handle Retry-After headers and similar info from
server
Motivation: some servers provide Retry-After header or similar info along with 429
or 503 status code, and it is often important to honor such information
on retries, i.e. simple expotential backoff is not optimal.
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online
2) Add option NOT to retry even if operation returns an error (but retry
by default, if no retry conditions are set)
Motivation: error are already passed to condition callback in resty, but
Backoff() still retries the request if error is not nil. It implies excessive,
stillborn retries for non-retryble errors from underlying http client
(i.e. with RoundTripper from …
=> change Backoff() algorithm

util.go
Sometime just want send fields without file when content-type is multipart/form-data
=> fix multipart/form-data without filename and content type

util.go
Simple optimisation to reduce memory allocations and copying(while appending).
=> Added capacity to slice creation, when capacity is known

middleware.go, resty_test.go, retry_test.go
Proves https://github.com/go-resty/resty/issues/289
=> Failing first request and successfully retrying carries error from first

request.go, request_test.go
Was working on a project recently that could have benefitted from something like this since the requests were constructed in a different place than they were actually sent.
You can already do this in Resty with something like this:
```
req := client.R()
req.URL = "http://httpbin.org/get"
req.Method = "GET"
resp, err := req.Execute(req.Method, req.URL)
```
It just feels a bit clunky to me.
=> Add Request.Send() method to execute Request as-is

request.go, request_test.go
Fixes #293
If EnableTrace has not been called prior to a request being made, an empty TraceInfo is returned rather than panicing
=> Fixed Panic When Calling TraceInfo But Tracing Has Not Been Enabled

client.go, middleware.go, request.go, request_test.go
To solve https://github.com/go-resty/resty/issues/281 
`(c *Client) SetDebugBodyLimit(sl int64)` of resty client works only on response logger,
but not request logger, resty will log the whole file content in strings when post files
This PR is trying to apply `SetDebugBodyLimit()` to request logger just like response logger. 
@jeevatkm
=> Apply debugBodySizeLimit to Request debug logger

README.md, client.go, client_test.go
Now it's impossible to set root certificate from string value, only from file path
=> added SetRootCertificateFromString method to read cert from string

client.go, client_test.go, go.mod, middleware.go, request.go, request_test.go
Took a quick pass at implementing this to address issue #306.
This PR adds a new Client/Request method named `SetAuthScheme` that allows the user to specify an Authorization header scheme. If one isn't set, the `addCredentials()` function will see this and default to using the "Bearer" scheme.
I'm a new Gopher so please be critical of the work!
=> Add ability to set Authorization header Scheme

context_test.go, resty_test.go, retry.go, retry_test.go
To fix retryCount not to include first attempt
I set SetRetryCount(1) since I wanted to be retried once, but never retried.
I found this issue is occurred by attempt loop which maximizes retryCount.
=> fix retry count

middleware.go, request.go, request_test.go, resty_test.go
=> #276 added force content type option for automatic unmarshalling

client.go, request.go, request_test.go, retry.go, util.go
This patch make default retry not on middlewares errors, which will make the retry action more sense and return error faster.
=> make default retry not on middlewares errors

middleware.go
It was calling `Debugf(debugLog)` which tries to handle `%` parameters, resulting in strange logs. Must be called this way instead `Debugf("%s", debugLog)`
=> Fixed Debugf call in Request/Response logguer

request.go, request_test.go, trace.go
=> Fix TraceInfo on failed connections

README.md, go.mod, resty.go
=> readme update, version bump, mod update

request.go, request_test.go
When a connection is reused, the normal trace hooks are skipped, which
led to an incorrect calculation of TotalTime (essentially doing a zero
minus now calculation). Detect connection reuse and use a different
calculation for TotalTime.
Fixes #346
=> Fix trace timing for reused connections

README.md
This PR adds an additional bullet about `Request.RawRequest`, since consumers may wrongly assume that the native request is available at all times but in fact it is only instantiated once the resty Request starts executing an action
=> README: Add clarification on Request.RawRequest

.travis.yml, client.go, client_test.go
This allows middlewares to properly access the RawRequest instance and follow their expected behavior according to OnBeforeRequest:
```
// OnBeforeRequest method appends request middleware into the before request chain.
// Its gets applied after default Resty request middlewares and before request
// been sent from Resty to host server.
```
=> Fix - request: execute user defined middlewares after resty's internal middlewares

client.go, request_test.go
When saving the response file, it was not recorded time.
as a result, incorrect calculation of response time.
=> Fix incorrect response time when saving the response file

README.md, middleware.go, request.go, request_test.go, resty.go, retry_test.go, trace.go
=> Couple of enhancements

client.go, middleware.go, request_test.go, resty_test.go
when the http status code is 307 or 308, the request.Body will be closed, after that the func GetBody will be called but the bodyBuf was closed, then we will get an error http: ContentLength=xxx with Body length 0
=> fix: get body size 0 (#300)

retry.go
Hello there.
The following commit fix the tests execution on 32bits arch. 
I have tested it on a armhf (32bit) Debian machine and confirm it's working.
Cheers!
Closes: https://github.com/go-resty/resty/issues/386
=> retry.go: Fix sleep computation for 32bit arch

README.md
It seems the example code in README uses previous function signature.
ref: https://github.com/go-resty/resty/releases/tag/v2.0.0
=> Fix documentation for retries in README

README.md, client.go, client_test.go, request.go
Adds a new hook that is called when a rest request returns an error.
This is called when the err returned by client.execute is non-nil, and
it is only called after all retry attempts have been exhausted.
This feature is intended to support logging, metrics, tracing on request
errors that otherwise cannot be captured with OnAfterResponse, such as
TLS Connection errors. It also provides a way to report response errors
only once after retries have been attempted, to avoid emitting error
logs when a request ultimately succeeds.
=> feature: add OnError hook

client.go, middleware.go, request.go, request_test.go
Closes #395 
Closes #387 
Closes #402
=> Enhancements

retry.go
Refactor sleepDuration function and use local random generatpr
=> refactor(retry.sleepDuration): :recycle: extract jitterBackoff function

client.go, client_test.go, retry_test.go
A really simple option so folks can set the retry options with easy and less verbosity in their code.
=> Added AddRetryAfterErrorCondition() option

client_test.go, request_test.go
I add a test for this behavior, I think it is a bug.
=> fix:when SetRetryCount -1, both resp and error are nil.

client.go, request.go, retry.go, retry_test.go
Add RetryHooks: side-effecting functions that will be executed whenever a retry is triggered.
RetryHooks give users the ability to add side-effecting operations whenever a retry is triggered, without having to abuse the RetryConditions or using the Backoff directly. For example, RetryHooks allow you to log whenever a retry is triggered.
Fixes #416
=> Feat: Add Retry hooks

README.md
The link https://github.com/orgs/go-resty/teams/core/members is broken (404 error)
Changing it to https://github.com/orgs/go-resty/people
=> Fix broken members link in readme

request.go, request_test.go
Implement easier adding of multiple value HTTP Header with function `SetMultiValueHeaders`
Closes #432
=> feat(#432): Implement Easier Adding of Multiple Value HTTP Header

BUILD.bazel, README.md, WORKSPACE
This includes several updates to the BUILD and WORKSPACE files, so that they now work with Bazel 4.0.0, Gazelle 0.23 and rules_go 0.27.
By default, [Gazelle now uses](https://github.com/bazelbuild/bazel-gazelle/pull/863) the last component of the Bazel package, rather than `go_default_library` as the `go_library name`.
This causes problems when the naming conventions do not match.
https://github.com/bazelbuild/bazel-gazelle/issues/890#issuecomment-685145667
Adding support for the new naming convention should not break anything that depends on using the old naming convention, because the Gazelle option `import_alias` makes aliases to the libraries and this allows the old naming convention to still work.
=> Update Bazel build to work with 4.0.0

client.go, middleware.go, request.go, util.go
The slice returned by `noescapeJSONMarshal` continues to be accessed
even after `pool.Put` was called on the buffer. This might lead to
incorrect data being sent in request body if the buffer is acquired and
re-written by a concurrently running goroutine.
=> Don't use sync.Pool for json.NewEncoder target buffers

retry.go, retry_test.go
Add check not to wait after last retry. Did it after retry hooks to keep compatibility.
Closes #443 
Signed-off-by: Pavel <kositsyn.pa@phystech.edu>
=> Don't wait after last retry

util.go, util_test.go
I stumbled on a bug when trying to send a multipart file that happened to be a gzip reader downloaded from elsewhere. Looks like the multipart content type detection logic doesn't handle `EOF` correctly. This can also be easily reproduced by sending an empty file (`bytes.NewReader(nil)`).
Here's a self contained example that reproduces the issue with a gzipped string:
```go
b := bytes.NewBuffer(nil)
w := gzip.NewWriter(b)
if _, err := w.Write([]byte("foo")); err != nil {
panic(err)
}
if err := w.Close(); err != nil {
panic(err)
}
r, err := gzip.NewReader(b)
if err != nil {
panic(err)
}
_, err = resty.New().NewRequest().SetFileReader("file", "foo.bar", r).Post("http://foo.bar")
if err != nil {
panic(err) // EOF!
}
```
----
Closes #431
=> Handle EOF from multipart form file readers

client.go, request.go
- Retry conditions can now also be added to Request
Closes #433 
Closes #315
Closes #324
=> Added RetryConditions to Request

.travis.yml, client.go, client_test.go, middleware.go, request_test.go
=> Addressing SetScheme option side effects on schemeless Host URL #407

client.go, middleware.go, util.go
=> Adding ability to customize the XML marshal/unmarshal functions #481

README.md, go.mod, go.sum, resty.go
Merge this PR after PR #484
Closes #486
=> For release v2.7.0 updates

request.go
I'm guessing the previous code was a typo and `client.R().Send()` would just send an empty request, not the configured `req`.
=> Fix Send() documentation code

client_test.go, middleware.go
Hi 👋 !
We detect some inconsistent behaviour of the current implementation of the  `SetAllowGetMethodPayload` based on the input type passed to `SetBody` option:
- SetAllowGetMethodPayload = false
- Body type = io.Reader => body is sent in GET
- Body type = non io.Reader => body is not sent in GET
- SetAllowGetMethodPayload = true
- Body type = io.Reader => body is sent in GET
- Body type = non io.Reader => body is sent in GET
Basically you can bypass the option AllowGetMethodPayload if you send an io.Reader as a Body, this fixes that for be consistent to all types and add a test case for test disabled option
=> Fix SetAllowGetMethodPayload option ignored for io.Reader payload

request.go, request_test.go
fixes #503.
Simply adds a `nil` check to `SetResult` to ensure that it can be used fluently. Also adds a simple unit test to ensure that the current panic will not happen any longer.
=> feat: add nil check to SetResult (#503)

client.go, middleware.go, request.go, request_test.go, resty_test.go
Working to integrate resty with [xop](https://github.com/muir/xop-go), I need request-scoped logs.  My need would be replicated by anyone else working to integrate resty with span/trace-based logging.
=> feat: add SetLogger() method on Request

client.go, client_test.go, context_test.go, request.go, request_test.go
Working to integrate resty with [xop](https://github.com/muir/xop-go), I need to be able to detect when a request is finished.  `OnError` already tracks one way a request could finish, but there are three other ways.
My need would be replicated by anyone else working to integrate resty with span/trace-based logging.
=> add OnSuccess, OnPanic, and OnInvalid hooks

client.go, redirect.go, request.go, response.go
Simply by running `go fmt` on the files
=> Reformat doc comments

client.go, go.mod, go.sum, request.go, resty_test.go, retry.go, retry_test.go
As mentioned in https://github.com/go-resty/resty/issues/166 by @neganovalexey, when doing a retry on a multipart request the `io.Reader` is not reset to the start again. This can lead to subtle bugs, as the request will be retried, but the form part of the file will be empty, because the reader was already exhausted. Solving this issue in the caller code is pretty ugly, because `Request` does not expose access to `multipartFiles` and so the caller would have to use `RetryHooks` and recreate the `Response.Request` and that at each call site (where there is access to the original `ReadSeeker`).
In the PR, I created a new client options `SetRetryResetReaders` which adds a retry hook  seeking the start of each reader in `multipartFiles`, if the reader it got also implements `io.ReadSeeker`. …
=> Fix multipart file readers not being reset when doing a retry

client_test.go, middleware.go, resty_test.go
As issue #567 described.
Copy the body buffer by buffer.Write to fix body mismatch with origin request when 307 or 308 redirect.
closes #567
=> Fix redirect request body mismatch with origin request body caused by buffer reused by mistake

client.go
Firstly, thanks for the wonderful library! It's an integral part of one of my team's projects and it works beautifully.
In our project, we have one resty client that performs all API requests. It is shared among multiple "users" that each inject their own auth tokens into each request via pre request hooks.
The issue is, if one user is performing requests at the same time as another user is being created (which involves setting up its pre-request hooks), our CI reports a data race.
Given that an API client such as resty is intended to be used in a highly parallel way, potentially by many different places in the code, it makes sense to me that user-modifiable things such as pre- and post-request hooks should be protected from data races. As such, I have added an RWMutex for each …
=> Fix race condition during request: Protect pre/post request hooks with RWMutex

README.md, client.go, client_test.go
Today I learned that I can set external JSON library for resty to marshal JSON faster. It wasn't so obvious because I haven't read the docs (let's be honest it's not only me who doesn't read docs), but there was no method for `resty.Client` to override JSON marshal function.
I suggest adding these `Set*` functions because this way they will be available through IDEs auto-completion.
=> client: setters for JSON and XML Marshal/Unmarshal

README.md, client.go, client_test.go, example_test.go, middleware.go, request_test.go, resty_test.go
io/ioutil has been deprecated since go1.16, and its functionality has been moved to io and os packages.
=> Remove usages of deprecated io/ioutil

client.go, client_test.go, digest.go, request.go, request_test.go, resty_test.go
- Adhere to RFC 7616 ("HTTP Digest Access Authentication")
- Added SetDigestAuth methods for Client and Request
- Currently not supporting auth-int Quality of Protection
closes #467
closes #572
=> Add digest authentication

retry.go, retry_test.go
rand.Rand.Int63n panics when passed a non-positive int. When maxWaitTime is 1ns, max/2 is zero.
Fixes #624
=> fix: jitter maxWaitTime must be >= 1ns

client_test.go, digest.go, resty_test.go
After splitting key=value pairs, we check that there are really key AND value. A maliciously crafted response header can cause the client to panic.
=> fix: client panic on missing digest value

middleware.go
=> fix sync pool data race: deep copy

client.go, client_test.go, request_test.go
=> feat: Export transport method to return current transport from the client

redirect.go
=> feat: export NoRedirectPolicy error

README.md
First of all, thank you for creating such a fantastic library. It has been incredibly useful in my work.
This PR enhances the README to provide more clarity on the default retry behavior and its interaction with `AddRetryCondition`. Specifically, the changes offer detailed explanations and examples to help users understand how retries work in Resty.
For reference, the current behavior which is not explicitly documented is based on the code found here: [retry.go L124-L131](https://github.com/go-resty/resty/blob/15cedd4f9ee3df956be40f38fa9b85fb529c8078/retry.go#L124-L131).
=> Enhance retry behavior documentation in README.md

client.go, middleware.go, request.go, request_test.go
Added `RawPathParams` options to `Client` and `Request` objects to support the path parameters with special characters, like `/`, without escaping.
Fix #663
Closes #570
=> Support RawPathParams without escaping

README.md
https://github.com/go-resty/resty/issues/16
https://github.com/go-resty/resty/issues/56
https://github.com/go-resty/resty/pull/107
Looks like `Request level proxy` has been removed, the description in the docs is confusing
=> update README.md about Proxy Settings, no Request level setting

middleware.go, response.go
fixes #652
fixes #653
fixes #678
=> Improve 204 no content handling

transport.go, transport_js.go, transport_other.go
those code copy from `/go/src/net/http/transport_default_other.go`
closes #610
=> improve: support js,wasm

.github/workflows/ci.yml, .github/workflows/label-actions.yml, README.md, client.go, client_test.go, middleware.go, redirect.go, request.go, request_test.go, resty.go
=> For v2.8.0 release

client_test.go, middleware.go
To address the issue https://github.com/go-resty/resty/issues/671 set `ContentLength` header to 0 when Body is `nil` and `setContentLength` was set to `true`.
Closes #671
=> Set ContentLength to 0 when Body is nil

client.go
The documentation about the order of middleware application for OnBeforeRequet was different from the implementation. Fixed this by changing the documentation.
Fixes https://github.com/go-resty/resty/issues/686.
=> docs: fix OnBeforeRequst doc application order

client.go, util_test.go
=> fix: improve regex expression for json and xml content type validation

README.md, client_test.go, resty_test.go
=> test: add test example for unix socket client and update readme #589

request_test.go
=> test: added validation test case, unable to reproduce #524

middleware.go
=> fix: correct url path params processing order #519

client.go, middleware.go
=> refactor: inherit value from client enables clean request overrides #516

BUILD.bazel
=> fix: add missing source files in the bazel build config #700

middleware.go
Reverts go-resty/resty#705
More info: https://github.com/go-resty/resty/pull/705#issuecomment-1732624745
=> Revert "fix: correct url path params processing order #519"

middleware.go, middleware_test.go
* unit tests for the `PathParams`, `RawPathParams` and `QueryParams` added by client and request
* unit tests for `client.HostURL` and `client.BaseURL`
* use `client.BaseURL` by default and fallback to `client.HostURL` if empty
=> unit tests for parseRequestURL function

client_test.go
In case of using `t.Parallel()` inside a for loop, the loop variables must be copied, otherwise only the last test will be executed.
```go
for _, test := range tests {
t.Run(test.name, func(t *testing.T) {
t.Parallel()
```
changed to
```go
for _, test := range tests {
test := test
t.Run(test.name, func(t *testing.T) {
t.Parallel()
```
also the AuthServer must be created within the test, otherwise some tests fail.
`t.Log(test.Name)` can be used to verify the issue:
```go
for _, test := range tests {
t.Run(test.name, func(t *testing.T) {
t.Parallel()
t.Log("Test name:", test.name)
```
=> fix TestClientOnResponseError parallel tests

middleware.go, middleware_test.go
Original benchmarks:
```shell
% go test -benchmem -bench=. -run=^Benchmark
goos: darwin
goarch: amd64
pkg: github.com/go-resty/resty/v2
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Benchmark_parseRequestHeader-16    1168611    1042 ns/op    496 B/op    8 allocs/op
```
After the improvements:
```shell
% go test -benchmem -bench=. -run=^Benchmark
goos: darwin
goarch: amd64
pkg: github.com/go-resty/resty/v2
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Benchmark_parseRequestHeader-16    7956481    155.6 ns/op    0 B/op    0 allocs/op
```
Improved by modifying the original request headers instead of creating a new object
=> Improve parseRequestHeader function and add the unit tests and benchmarks

middleware.go, middleware_test.go
Improve the `parseRequestBody` function and all nested functions.
Original benchmarks:
```shell
% go test -benchmem -bench=. -run=^Benchmark
goos: darwin
goarch: amd64
pkg: github.com/go-resty/resty/v2
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Benchmark_parseRequestBody_string-16       2199196    550.3 ns/op     128 B/op      3 allocs/op
Benchmark_parseRequestBody_byte-16         2264421    532.9 ns/op     128 B/op      3 allocs/op
Benchmark_parseRequestBody_reader-16       8307141    141.8 ns/op      16 B/op      1 allocs/op
Benchmark_parseRequestBody_struct-16        931632     1317 ns/op     156 B/op      5 allocs/op
Benchmark_parseRequestBody_struct_xml-16    409074     2921 ns/op    4765 B/op     13 allocs/op
Benchmark_parseRequestBody_map-16           566750     2158 ns/op …
```
=> Add Benchmarks and Unit tests for parseRequestBody and improve it

middleware.go, middleware_test.go
The benchmarks for the applying PathParams and adding QueryParams.
Original results:
```shell
% go test -benchmem -bench=. -run=^Benchmark
goos: darwin
goarch: amd64
pkg: github.com/go-resty/resty/v2
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Benchmark_parseRequestURL_PathParams-16    524658    2260 ns/op    448 B/op     9 allocs/op
Benchmark_parseRequestURL_QueryParams-16   865923    1371 ns/op    416 B/op    13 allocs/op
```
After the improvements:
```shell
% go test -benchmem -bench=. -run=^Benchmark
goos: darwin
goarch: amd64
pkg: github.com/go-resty/resty/v2
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Benchmark_parseRequestURL_PathParams-16     753834    1367 ns/op    256 B/op    5 allocs/op
Benchmark_parseRequestURL_QueryParams-16   1000000    1167 ns/op    352 B/op    9 …
```
=> Benchmarks and Improvements for parseRequestURL function

request_test.go, response.go, retry_test.go
=> feat(enhancement): add SetBody method in Response struct #721

middleware.go
This fixes #743, possibly #739.
Discovered this while tracking down an issue in https://github.com/linode/terraform-provider-linode.
The removed call to sync.Pool.Put is handled by the request body wrapper that puts the buffer back in the pool when the body is closed.
=> Security: Don't put the same bytes.Buffer into sync.Pool twice

digest.go
Improve Digest WWW-Authenticate response header parsing compatibility
1. Use commas to disassemble WWW-Authenticate instead of commas and spaces.
2. Clear the spaces before and after each key-value pair.
3. Added double quote clearing operation for stale and algorithm values.
=> fix: Improve Digest WWW-Authenticate response header parsing compatibility

middleware.go
Fixing simple typo in `middleware.go`.
=> fix: doc typo

README.md
`SetHostURL` is deprecated, it will be removed in v3.0.0 release.
=> docs: replace `SetHostURL` to `SetBaseURL`

client_test.go, request.go
`noescapeJSONMarshalIndent` must either copy the buffer data or don't put it into the sync.Pool (similar to `noescapeJSONMarshal`). Otherwise, we could have a data race:
```
$ go test -run TestDebugLogSimultaneously -race
==================
WARNING: DATA RACE
Write at 0x00c00001e8c0 by goroutine 31:
runtime.slicecopy()
/usr/lib/go/src/runtime/slice.go:325 +0x0
bytes.(*Buffer).Write()
/usr/lib/go/src/bytes/buffer.go:181 +0x118
github.com/go-resty/resty/v2.jsonMarshal()
/home/buglloc/work/projects/resty/util.go:164 +0x158
github.com/go-resty/resty/v2.handleRequestBody()
/home/buglloc/work/projects/resty/middleware.go:507 +0x2e7
github.com/go-resty/resty/v2.parseRequestBody()
/home/buglloc/work/projects/resty/middleware.go:193 +0x290
github.com/go-resty/resty/v2.(*Client).execute() …
```
=> Fixed JSON request logging data race.

middleware_test.go, util.go
=> fix: trailing NULL bytes in buffer while detecting a content type

client.go, client_test.go
This adds a crude cloning function. It can be used to have a main client with default values and then create copies from that, which must use custom values.
The added function is rather crude and may introduce the potential that, when adding a new Client field, we forget to add it to Clone.
Thus, we should discuss if this is the right way to go. Using code generation or relflection might be a more maintainable solution.
Merging this PR would close #773
=> Add Client.Clone function

.github/workflows/ci.yml, .github/workflows/label-actions.yml
actions/checkout@v4
actions/setup-go@v5
both have faster runtime (node 20) and bugfixes
=> build: update github actions

client_test.go, digest.go, resty_test.go
This re-implements parsing the digest challenge to fix authentication against servers returning multiple values for `qop`.
Take this example from https://httpwg.org/specs/rfc7616.html:
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Digest
realm="http-auth@example.org",
qop="auth, auth-int",
algorithm=SHA-256,
nonce="7ypf/xlj9XXwfDPEoM4URrv/xwf94BcCAzFZH4GiTo0v",
opaque="FQhe/qaU925kfnzjCev0ciny7QMkPqMAFRtzCUYo5tdS"
```
Here qop is set to `qop="auth, auth-int"`. Because the previous parser split the entire list by comma to obtain the key value pairs this gets separated into `qop="auth` and ` auth-int"`, which eventually failes to parse.
The new parser goes over the challenge rune by rune and does not split when inside a quotation.
Also some servers will respond with `qop="auth,auth-int"` …
=> Fix digest auth

.github/workflows/ci.yml, .github/workflows/label-actions.yml, .gitignore, README.md, client.go, examples/debug_curl_test.go, examples/server_test.go, middleware.go, request.go, shellescape/shellescape.go, util_curl.go
I've extracted curl code from my previous PR(https://github.com/go-resty/resty/pull/734). 
Could you review this code?
Example: https://github.com/ahuigo/resty/blob/curl/v2/examples/debug_curl_test.go
```
var curlCmdExecuted string
client := resty.New()
_, err := client.R().
SetResultCurlCmd(&curlCmdExecuted).
Get("https://httpbin.org/get")
// Explore curl command
fmt.Println("Curl Command:", curlCmdExecuted)
```
```
$ go test -run '^TestDebugCurl$' github.com/go-resty/resty/v2/examples -v
=== RUN   TestDebugCurl
debug_curl_test.go:29: curlCmdUnexecuted:  
curl -X GET -H 'Content-Type: application/json' -H 'Cookie: count=1' -H 'User-Agent: go-resty/2.12.0 (https://github.com/go-resty/resty)' -d '{"name":"Alex"}' 'http://unexecuted-url'
debug_curl_test.go:41: curlCmdExecuted:  
curl -X …
```
=> feat(curl): generate curl cmd for request && example for curl cmd

examples/debug_curl_test.go
=> fix(examples): wrongly stderr written as stdout

request.go
This PR fixes doc comment of `Request.Send()` and `Request.Execute()`.
`resty.GET` is renamed to `resty.MethodGet` at f990acd78d27c0d2ba18e219b459d92468fd4f4f.
However, these comments were left out.doc comment.
=> fix: change resty.GET to resty.MethodGet in doc comment

middleware.go, request.go, request_test.go
Integrating with some web service that require a specific boundary format in multipart/form-data requests.
Some legacy service might requires a specific prefix in the boundary value, to ensure the compatibility, we need the ability to set a custom boundary value in the multipart request.
```go
package main
import (
"crypto/rand"
"fmt"
"io"
"log"
"github.com/go-resty/resty/v2"
)
const BoundaryPrefix = "Some_MultiPart_Prefix_"
func randomBoundary() string {
var buf [4]byte
_, err := io.ReadFull(rand.Reader, buf[:])
if err != nil {
panic(err)
}
return fmt.Sprintf("%s_%X", BoundaryPrefix, buf[:])
}
func main() {
// Initialize the client
client := resty.New()
// Perform the file upload
_, err := client.R().
SetMultipartFormData(map[string]string{"test": "1"}).
SetBoundary(randomBoundary()) // …
```
=> feat: add ability to set custom multipart boundary value

client.go, client_test.go, request.go, resty_test.go, retry_test.go
Client not will be able to check resposne body size limit.
If server return a large response than expected, it will discard the response and return a err `ErrResponseBodyTooLarge`. 
```golang
c := Client().SetResponseBodyLimit(1024*1024*1024) // do not allow body larger than 1GiB
res, err := c.R().Get(...)
if err != nil{
if errors.Is(err, resty.ErrResponseBodyTooLarge){
...
}
}
```
close https://github.com/go-resty/resty/issues/819
=> feat: add max reponse body limit

client.go, client_test.go, resty.go
=> feat(enhancement): add ability to override default value and provide transport settings on resty client #814

client.go, client_test.go, middleware.go, middleware_test.go, request.go, request_test.go, resty.go, retry.go, retry_test.go, util.go
Refer to https://github.com/go-resty/resty/issues/812 for more info.
closes #812
=> feat: add mutex to make Client thread-safe

.github/workflows/ci.yml, .github/workflows/label-actions.yml, client.go, client_test.go, go.mod, middleware.go, middleware_test.go, request.go, request_test.go, response.go, util.go
=> feat(enhancement): inherit client values in the request during a creation and use it afterwards #796

resty.go
This PR fixes the reverse merge issue that occurred on branch `main` from `v2`.
=> fix: add missing middleware for generating curl command

client.go, client_test.go
support setting custom clientCAs cert
=> feat: add SetClientRootCertificate method support clientCAs usage

client_test.go, request.go, request_test.go, resty.go, util.go, util_test.go
=> feat: add `Clone` method for Request

client.go, request.go, retry_test.go
=> feat: add retry settings method at request level #752

client.go, middleware.go, middleware_test.go, request.go, request_test.go, resty_test.go, stream.go, util.go, util_curl.go
=> feat(continue)!: add content type encoder and decoder, implement encoder in the request generation flow #439

client.go, util.go, util_test.go
As it turns out, `errors.Join` is not playing well with simple errors like `errors.New` or `fmt.Errorf`.  For now, let's go with a custom error with `Unwrap`.
=> fix: do not use errors.Join, just use custom error approach

.github/workflows/ci.yml, .github/workflows/label-actions.yml, client.go, client_test.go, go.mod, middleware.go, middleware_test.go, response.go, resty.go, resty_test.go, stream.go, util_test.go
=> Content decompressors and go min version update

middleware.go
An error like ‘dial tcp 10.66.0.229:80: connect: connection refused’ when request and response logging is activated causes an ‘invalid memory address or nil pointer dereference’. This is due to changes from version 2.14 to 2.15, where the logging call was moved up in the execute function. In version 2.14, the function returned early on this error, so the logging call was not made. Now, the logging call is made, and res.RawResponseProto is used without a nil check on RawResponse.
The fix is simple: use res.Proto(), which performs the nil check.
fixes #873
=> fix: 'invalid memory address or nil pointer dereference' in response logger

client.go, client_test.go, context_test.go, middleware.go, request.go, request_test.go, resty_test.go, util.go
=> feat: add context concept into client and update request flow with features #722

middleware.go, request.go
closes #496 
The solution is not to use the method `Get` on the Header, which returns an empty string for a non-existing header key. Instead, check directly in the header map
=> feat: add way to set empty header on request #496

middleware.go, middleware_test.go
=> Remove setcontentlength from reader flow

client.go, middleware.go, middleware_test.go, request.go, resty_test.go
=> feat: option to set URL query params without encoding

README.md, client.go, load_balancer.go, load_balancer_test.go, middleware.go, middleware_test.go, request.go, request_test.go
=> feat!: add load balancer with couple of algorithms OOTB, lb interface is extensible #430 #274

README.md, client.go, client_test.go, context_test.go, middleware.go, request.go, request_test.go, resty.go, resty_test.go, retry.go, retry_test.go, util.go, util_test.go
=> feat!: redesign request retry flow, retry-after header, default retry conditions #886

multipart_test.go, request.go, request_test.go, resty_test.go, retry_test.go
=> feat: retry only idempotent methods #777

client.go, client_test.go, redirect.go
=> feat(redirect)!: update error type on no redirect policy and cleanup #893

cert_watcher_test.go, client.go, client_test.go, request_test.go
=> feat!: add TLSClientConfiger interface to support TLSClientConfig for custom round tripper #377

README.md, client.go, client_test.go, middleware.go, middleware_test.go, multipart_test.go, request.go, request_test.go, resty.go, util.go
- PreRequestHook removed
- Resty request and response middleware become exported
- Any order of middleware insertion is feasible
Closes #811
Closes #345
Closes #665
Closes #747
=> feat!: add fully composable request and response middleware

middleware.go, multipart.go, multipart_test.go, request.go, resty_test.go
=> feat: add ability to do mutlipart ordered formdata along with file(s) #669

request.go, retry_test.go, util.go, util_test.go
=> feat: add retry trace id and attempt details into debug log #897

client.go, client_test.go, curl.go, curl_test.go, load_balancer.go, load_balancer_test.go, middleware.go, redirect.go, request.go, response.go, stream.go, util.go
- curl cmd request body error scenario and removed pointer on string
- redirect add error prefix and remove default header
- test case additions
=> refactor(enhancement): use std lib functions

client.go, client_test.go, digest.go, example_test.go, middleware.go, request.go, request_test.go, resty.go, resty_test.go, util.go
- User type become unexported 
- HTTP not secure warning message added for auth token flow too
- Intialize the default auth scheme value `Bearer` during client creation
=> feat!: enhance credentials usage and update warning message for credentials requests

README.md, client.go, request.go, request_test.go, resty.go, util.go
=> fix: buffer reuse and back to pool and release v2.16.2

client.go, client_test.go, context_test.go, request.go, request_test.go, retry_test.go
- add Request.SetTimeout method
closes #545
=> feat: use context timeout instead of http client timeout option #545

.github/workflows/ci.yml, .github/workflows/label-actions.yml, benchmark_test.go, client.go, client_test.go, curl_test.go, digest.go, digest_test.go, go.mod, go.sum, middleware.go, middleware_test.go, multipart_test.go, request.go, request_test.go, response.go, resty.go, resty_test.go, stream.go
- correct digest roundtrip return value on error scenario
- streamline content-length value on buffer and partial io.Reader flow
- correct typo of ContentDecompressor -> ContentDecompressor
- refactor createHTTPRequest -> createRawRequest
- update c.log -> c.Logger()
- update redundant err check and if conditions
- address curl cmd non-execute request error flow
- prevent reset buffer during buffer copy on request clone
- improve test cases and corner coverage
- move benchmarks into a dedicated file
- update godoc
=> feat(enhancement): remove unnecessary map for raw path params instead use path params

client.go, resty_test.go, retry.go, sse.go, sse_test.go
=> feat: add server-sent events client #658

client.go, middleware.go, middleware_test.go, request.go, request_test.go, resty_test.go, util.go
=> feat: auto parse filename from content-disposition or URL #926

circuit_breaker.go, client.go, client_test.go
Adds a circuit breaker to resty.Client which disables requests for a specified period of time upon multiple failures.
Default behavior is counting 5xx errors, but users can implement their own policies.
Resolves #448
=> feat: Client Circuit Breaker

client.go, curl.go, curl_test.go, middleware.go, request.go, resty.go, util.go
=> feat(enhancement)!: seperate generate curl cmd from debug flow #928
